### ISSUE TITLE
New version of smatchpp 1.3.0

### ISSUE THREAD

**Issue by flipz357** [BramVanroy/multilingual-text-to-amr#9]
Interesting project! Just to let you know, with version 1.3.0 smatch++ should now be a bit faster. The final score may also be changed a tiny bit since I modified a small part in the standardization, to recognize that in AMR guideline `x :domain y` is considered same as `x :mod-of y` respectively `y :mod x`.

(just opened this issue to let you know, I'm gonna close it soon)

**Comment by BramVanroy** [comment]
@flipz357  Thanks for letting me know, Juri. I have currently pinned smatchpp to 1.1.3 for reproducibility. In the feature, I will likely update to your newer version. Thanks for letting me know that I can expect some differences in scores!
